---
language: python
python:
  - "2.7"

# Install python packages for ansible and linters.
install:
  - "pip install -r requirements.txt"

# Execute linting and unit tests before running the main playbook.
before_script:
  - "find . -name '*.yml' | xargs yamllint -s"

# Perform playbook testing with mock CI inputs.
script:
  - "ansible-playbook test_playbook.yml -i hosts.yml"
