---
# Define the language and version used. The CI system will create
# a Python virtualenv for this particular version for the test.
language: "python"
python:
  - "2.7"

# Install python packages for ansible and linters first.
install:
  - "pip install -r requirements.txt"

# Execute linting to catch minor errors before running the main playbook.
# If you have a directory hierarchy, use this style instead:
# "find . -name '*.yml' | xargs yamllint -s"
before_script:
  - "yamllint -s *.yml"

# Perform playbook testing with on a pre-existing virtual router.
script:
  - "ansible-playbook test.yml"
