---
- name: "Import original playbook with modified inputs"
  import_playbook: "ntp_playbook.yml"
  vars:
    ntp_server1: "203.0.113.1"
    ntp_server2: "203.0.113.2"

- name: "Log into routers to test playbook"
  hosts: all
  connection: network_cli
  gather_facts: false
  tasks:
    - name: "TASK 1: Gather mock NTP data after enabling NTP"
      ios_command:
        commands: "show ntp associations"
      register: ntp_associations

    - name: "TASK 2: Check that mock NTP data is present"
      assert:
        that:
          - "'203.0.113.1' in ntp_associations.stdout[0]"
          - "'203.0.113.2' in ntp_associations.stdout[0]"
        msg: "Missing some NTP data:\n{{ ntp_associations.stdout[0] }}"

    - name: "TASK 2: Disable NTP"
      ios_config:
        commands: "no ntp"

    - name: "TASK 3: Wait 2 seconds"
      pause:
        seconds: 2

    - name: "TASK 4: Gather mock NTP data after disabling NTP"
      ios_command:
        commands: "show ntp associations"
      register: ntp_associations

    - name: "TASK 5: Check mock NTP data is absent"
      assert:
        that:
          - "'203.0.113.1' not in ntp_associations.stdout[0]"
          - "'203.0.113.2' not in ntp_associations.stdout[0]"
        msg: "Saw some NTP data:\n{{ ntp_associations.stdout[0] }}"
...
